/*
static char sccs_id[] = "@(#)uwinoptP.h	5.5  9/1/88";
*/

/*
 * Copyright 1988 by Siemens Research and Technology Laboratories, Princeton, NJ
 *
 *                         All Rights Reserved
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose and without fee is hereby granted,
 * provided that the above copyright notice appear in all copies and that
 * both that copyright notice and this permission notice appear in
 * supporting documentation, and that the name of Siemens Research and Technology
 * Laboratories not be used in advertising or publicity pertaining to
 * distribution of the software without specific, written prior permission.
 *
 *
 * SIEMENS DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING
 * ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO EVENT SHALL
 * SIEMENS BE LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR
 * ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS
 * SOFTWARE.
 */


typedef enum {

    ACCEPT_BUTTON_IN_BODY,
    ACCEPT_BUTTON_IN_HEADER,
    ACCEPT_BUTTON_IN_ICON,

    ACCEPT_KEY_IN_BODY,
    ACCEPT_KEY_IN_HEADER,
    ACCEPT_KEY_IN_GADGET,
    ACCEPT_KEY_IN_BORDER, 
    ACCEPT_KEY_IN_ICON,

    AGGRESSIVELY_REPOPULATE,

    ALLOW_SHRINK_ON_UNZOOM, 
    ALLOW_SHRINK_ON_AUTO_UNZOOM, 

    ALLOW_ZOOM_CLOSE,

    AUTO_OPEN_ON_CREATE, 
    AUTO_OPEN_ON_WRITE, 

    AUTO_PLACE_ON_CLIENT_OPEN,

    AUTO_RESATISFY_ON_RESET_MINMAX,

    CLIENT_DRAWS_ICON,
    CLIENT_PROVIDES_HEADER,

    CONSIDER_FOR_REPOPULATION,

    ENFORCE_CLIENT_MINIMUMS,
    ENFORCE_CLIENT_MAXIMUMS,

    LISTENER_TIED_TO_ZOOM,

    FORCE_SHRINK_ON_UNZOOM, 
    FORCE_SHRINK_ON_AUTO_UNZOOM, 

    GLASS_CLIENT,

    ICON_DRAWN_BY_CLIENT,

    IGNORE_INITIAL_POSITION_HINTS,
    IGNORE_INITIAL_SIZE_HINTS,
    IGNORE_POSITION_HINTS,
    IGNORE_SIZE_HINTS,

    INCLUDE_RES_CLASS_IN_TITLE,
    INCLUDE_RES_CLASS_IN_ICON_TITLE,
    INCLUDE_RES_NAME_IN_TITLE,
    INCLUDE_RES_NAME_IN_ICON_TITLE,
    INCLUDE_NAME_IN_TITLE,
    INCLUDE_NAME_IN_ICON_TITLE,
    INCLUDE_HOST_IN_TITLE,
    INCLUDE_HOST_IN_ICON_TITLE,

    INCLUDE_TITLE_IN_HEADER,
    INCLUDE_TITLE_IN_PIXMAP_ICON,
    INCLUDE_TITLE_IN_CLIENT_ICON,

    INVERT_ICON_WHEN_PENDING,

    NOTE_LISTENER,
    NOTE_LISTENER_INPUT,
    NOTE_CLOSED_INPUT,
    NOTE_OPEN_INPUT,
    NOTE_CLOSED_OUTPUT,
    NOTE_OPEN_OUTPUT,

    PREFER_PREVIOUS_ICON_POSITION,
    PREFER_PREV_POS,
    REQUIRE_PREVIOUS_ICON_POSITION,
    REQUIRE_PREV_POS,

    SAVE_IN_LAYOUT,

    SHOW_ICON,

    USE_BORDERS,
    USE_GADGETS,
    USE_HEADER,
    USE_MOVE_GADGET,

    ZOOM_FULL_EXPLICIT,
    ZOOM_FULL_HEIGHT,
    ZOOM_FULL_WIDTH,

    ZOOM_ON_OPEN,

    ZOOM_TIED_TO_DESIRE,

    LENGTH_USER_WINDOW_OPTIONS
 } User_Window_Options;
